# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in file in `custom`

# Defaults
source=~/.config/hypr/hyprland/env.conf
source=~/.config/hypr/hyprland/execs.conf
source=~/.config/hypr/hyprland/general.conf
source=~/.config/hypr/hyprland/rules.conf
source=~/.config/hypr/hyprland/colors.conf
source=~/.config/hypr/hyprland/keybinds.conf

# Custom 
source=~/.config/hypr/custom/env.conf
source=~/.config/hypr/custom/execs.conf
source=~/.config/hypr/custom/general.conf
source=~/.config/hypr/custom/rules.conf
source=~/.config/hypr/custom/keybinds.conf

#input method
#setup
exec-once = export GTK_IM_MODULE=fcitx5
exec-once = export QT_IM_MODULE=fcitx5
exec-once = export XMODIFIERS=@im=fcitx5
exec-once = export INPUT_METHOD=fcitx5
exec-once = export SDL_IM_MODULE=fcitx5
#auto start
exec-once = fcitx5

bind = Super, P, exec, hyprshot -m region
bind = Super, R, exec, kitty fish -c "vifm"

# Resize
bind = Super, LEFT, resizeactive, -50 0
bind = Super , RIGHT, resizeactive, 50 0
bind = Super, UP, resizeactive, 0 -50
bind = Super, DOWN, resizeactive, 0 50

# Move
# bind = CTRL, LEFT, moveactive, -50 0
# bind = CTRL, RIGHT, moveactive, 50 0
# bind = CTRL, UP, moveactive, 0 -50
# bind = CTRL, DOWN, moveactive, 0 50
# Move Focus Window
# bind = $mainMod, I, movewindow, u
# bind = $mainMod, K, movewindow, d
# bind = $mainMod, J, movewindow, l
# bind = $mainMod, L, movewindow, r
